application: alexastocks
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: ssl
  version: latest
